-- ═══════════════════════════════════════════════════════════════════════════
-- PracticeOS Lite Pre-Production Resume Script
-- Audit date:    2026-04-30
-- Project:       wlkwmfxmrnjqvcsbwksk (PracticeOS Lite)
-- Author:        Generated by audit on 2026-04-30
--
-- WHAT THIS DOES
-- Flips every paused cron job + disabled trigger to live state. Run on go-live
-- after final smoke testing in test mode. Run section-by-section, verifying
-- each block before moving to the next.
--
-- WHAT THIS DOES NOT DO
-- - The IC-BOS Supabase project (cofhgphltpykchidshds) has its own paused
--   crons (onboarding_daily_check, automation_health_monitor, task_due_date_alerts,
--   renewal_90day_alert, collections_review, weekly_digest). Run an equivalent
--   script there.
-- - Does NOT touch operational items: Stripe live keys, Twilio A2P registration,
--   BAA paperwork, sftpgo lockdown, AI compliance line items.
--
-- ALREADY ACTIVE (do not flip — these are running now)
-- - pro_insurance_ocr_backfill (jobid 12)
-- ═══════════════════════════════════════════════════════════════════════════


-- ───────────────────────────────────────────────────────────────────────────
-- SECTION 1: PRACTICEOS LITE PORTAL AUTOMATIONS (2 crons)
-- ───────────────────────────────────────────────────────────────────────────
SELECT cron.alter_job(job_id :=  6::bigint, active := true);  -- pos_lite_notifications_backfill (every 10 min)
SELECT cron.alter_job(job_id :=  7::bigint, active := true);  -- pos_lite_balance_reminder       (Mon 13:00 UTC)


-- ───────────────────────────────────────────────────────────────────────────
-- SECTION 2: PRO-TIER CHART PREP AUTOMATIONS (3 crons)
-- ───────────────────────────────────────────────────────────────────────────
SELECT cron.alter_job(job_id :=  8::bigint, active := true);  -- pro_chart_prep_nightly  (22:00 UTC daily)
SELECT cron.alter_job(job_id :=  9::bigint, active := true);  -- pro_chart_prep_retry    (every 10 min)
SELECT cron.alter_job(job_id := 10::bigint, active := true);  -- pro_chart_prep_watchdog (11:00 UTC daily)


-- ───────────────────────────────────────────────────────────────────────────
-- SECTION 3: COMMAND-TIER SCRIBE AUDIO PURGE (1 cron)
-- ───────────────────────────────────────────────────────────────────────────
SELECT cron.alter_job(job_id := 13::bigint, active := true);  -- cmd_scribe_audio_purge (hourly :17)


-- ───────────────────────────────────────────────────────────────────────────
-- SECTION 4: AMH INBOUND PARSERS (5 crons — all Tuesdays staggered hourly)
-- ───────────────────────────────────────────────────────────────────────────
SELECT cron.alter_job(job_id := 14::bigint, active := true);  -- amh_member_assignment_parse_weekly  (Tue 13:00 UTC)
SELECT cron.alter_job(job_id := 15::bigint, active := true);  -- parse-amh-claim-professional       (Tue 14:00 UTC)
SELECT cron.alter_job(job_id := 16::bigint, active := true);  -- parse-amh-claim-dental-weekly      (Tue 15:00 UTC)
SELECT cron.alter_job(job_id := 17::bigint, active := true);  -- parse-amh-claim-institutional-weekly (Tue 16:00 UTC)
SELECT cron.alter_job(job_id := 18::bigint, active := true);  -- parse-amh-claim-pharmacy-weekly    (Tue 17:00 UTC)


-- ───────────────────────────────────────────────────────────────────────────
-- SECTION 5: HEDIS OUTBOUND MONTHLY CRON (1 cron)
-- ───────────────────────────────────────────────────────────────────────────
SELECT cron.alter_job(job_id := 19::bigint, active := true);  -- hedis_outbound_monthly_check (07:00 UTC daily)


-- ═══════════════════════════════════════════════════════════════════════════
-- VERIFY CRONS — every row should show active=true
-- ═══════════════════════════════════════════════════════════════════════════
-- SELECT jobid, jobname, schedule, active
-- FROM cron.job
-- WHERE jobid IN (6,7,8,9,10,12,13,14,15,16,17,18,19)
-- ORDER BY jobid;


-- ═══════════════════════════════════════════════════════════════════════════
-- SECTION 6: PORTAL DISPATCH TRIGGERS (6 triggers)
-- AFTER INSERT triggers that POST to run-notifications via pg_net helper
-- ═══════════════════════════════════════════════════════════════════════════
ALTER TABLE public.insurance_update_requests ENABLE TRIGGER trg_insurance_update_dispatch;
ALTER TABLE public.lab_results               ENABLE TRIGGER trg_lab_released_dispatch;
ALTER TABLE public.messages                  ENABLE TRIGGER trg_portal_message_dispatch;
ALTER TABLE public.portal_form_submissions   ENABLE TRIGGER trg_form_submission_dispatch;
ALTER TABLE public.portal_notifications      ENABLE TRIGGER trg_portal_notification_dispatch;
ALTER TABLE public.refill_requests           ENABLE TRIGGER trg_refill_ack_dispatch;


-- ═══════════════════════════════════════════════════════════════════════════
-- SECTION 7: CARE-MANAGEMENT AUTO-RISK TRIGGERS (2 triggers)
-- Auto-flags clinical risk when failed-touchpoint count crosses UTR threshold
-- or when an urgent HRSN screener response comes in
-- ═══════════════════════════════════════════════════════════════════════════
ALTER TABLE public.cm_touchpoints     ENABLE TRIGGER trg_auto_risk_on_utr_threshold;
ALTER TABLE public.screener_responses ENABLE TRIGGER trg_auto_risk_on_urgent_hrsn;


-- ═══════════════════════════════════════════════════════════════════════════
-- SECTION 8: HEDIS RECONCILE TRIGGER (1 trigger)
-- AFTER INSERT on cm_clinical_evidence: auto-closes matching open HEDIS gaps
-- ═══════════════════════════════════════════════════════════════════════════
ALTER TABLE public.cm_clinical_evidence ENABLE TRIGGER trg_reconcile_hedis_on_evidence;


-- ═══════════════════════════════════════════════════════════════════════════
-- VERIFY TRIGGERS — every row should show tgenabled='O' (origin/enabled)
-- ═══════════════════════════════════════════════════════════════════════════
-- SELECT n.nspname||'.'||c.relname AS table_full, t.tgname, t.tgenabled
-- FROM pg_trigger t
-- JOIN pg_class c ON c.oid = t.tgrelid
-- JOIN pg_namespace n ON n.oid = c.relnamespace
-- WHERE NOT t.tgisinternal AND n.nspname = 'public'
--   AND t.tgname IN (
--     'trg_insurance_update_dispatch','trg_lab_released_dispatch',
--     'trg_portal_message_dispatch','trg_form_submission_dispatch',
--     'trg_portal_notification_dispatch','trg_refill_ack_dispatch',
--     'trg_auto_risk_on_utr_threshold','trg_auto_risk_on_urgent_hrsn',
--     'trg_reconcile_hedis_on_evidence'
--   )
-- ORDER BY table_full, tgname;


-- ═══════════════════════════════════════════════════════════════════════════
-- TOTAL: 12 cron jobs + 9 triggers flipped on
-- (12 crons because pro_insurance_ocr_backfill jobid 12 was already active.)
--
-- SAFETY: Every statement is idempotent. Running this script twice has no
-- ill effect — already-active jobs/triggers stay active.
-- ═══════════════════════════════════════════════════════════════════════════
